name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main # (Ubah menjadi master jika default branch repositori adalah master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Mengunduh Kode Repositori
        uses: actions/checkout@v4

      - name: 2. Konfigurasi Python Lingkungan
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Pematokan versi setuptools<70.0.0 untuk kompatibilitas pkg_resources pada MLflow 2.11.3
      - name: 3. Instalasi Pustaka Pendukung & MLflow
        run: |
          python -m pip install --upgrade pip
          pip install "setuptools<70.0.0" wheel
          pip install pandas scikit-learn matplotlib seaborn mlflow==2.11.3

      # Penyuntikan MLFLOW_TRACKING_URI & kredensial DagsHub untuk mencegah galat Run not found
      - name: 4. Mengeksekusi Pelatihan Model (MLflow Project)
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: "pedro-muqoyat"
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: "https://dagshub.com/pedro-muqoyat/Eksperimen_SML_lifani.mlflow"
        run: |
          mlflow run . --env-manager=local

      # Peningkatan ke v3 untuk kompatibilitas Node 24 & Resolusi Kredensial Docker Hub
      - name: 5. Autentikasi ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 6. Kompilasi & Distribusi Docker Image (Advanced Kriteria)
        run: |
          echo "[INFO] Menambahkan pengaman dependensi ke requirements.txt model..."
          if [ -f "local_model_dir/requirements.txt" ]; then
            # [KOREKSI DI SINI] Menambahkan baris kosong (enter) agar teks tidak saling menempel
            echo "" >> local_model_dir/requirements.txt
            echo "setuptools<70.0.0" >> local_model_dir/requirements.txt
          fi

          echo "[INFO] Merancang Dockerfile MLOps terisolasi berbasis Python 3.12-Slim..."
          cat <<EOF > Dockerfile
          FROM python:3.12-slim
          WORKDIR /opt/mlflow
          COPY local_model_dir ./model
          RUN apt-get update && apt-get install -y --no-install-recommends build-essential && \
              pip install --no-cache-dir --upgrade pip && \
              pip install --no-cache-dir "setuptools<70.0.0" wheel && \
              pip install --no-cache-dir -r ./model/requirements.txt && \
              pip install --no-cache-dir mlflow==2.11.3
          EXPOSE 5001
          CMD ["mlflow", "models", "serve", "-m", "./model", "-h", "0.0.0.0", "-p", "5001", "--env-manager=local"]
          EOF

          echo "[INFO] Memulai eksekusi kompilasi Docker (Build)..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/klasifikasi-mahasiswa-api:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/klasifikasi-mahasiswa-api:latest
