name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main # (Ubah menjadi master jika default branch repositori adalah master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Mengunduh Kode Repositori
        uses: actions/checkout@v4

      - name: 2. Konfigurasi Python Lingkungan
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Pematokan versi setuptools<70.0.0 untuk kompatibilitas pkg_resources pada MLflow 2.11.3
      - name: 3. Instalasi Pustaka Pendukung & MLflow
        run: |
          python -m pip install --upgrade pip
          pip install "setuptools<70.0.0" wheel
          pip install pandas scikit-learn matplotlib seaborn mlflow==2.11.3

      # Penyuntikan MLFLOW_TRACKING_URI & kredensial DagsHub untuk mencegah galat Run not found
      - name: 4. Mengeksekusi Pelatihan Model (MLflow Project)
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_USERNAME: "pedro-muqoyat"
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
          MLFLOW_TRACKING_URI: "https://dagshub.com/pedro-muqoyat/Eksperimen_SML_lifani.mlflow"
        run: |
          mlflow run . --env-manager=local

      # Peningkatan ke v3 untuk kompatibilitas Node 24 & Resolusi Kredensial Docker Hub
      - name: 5. Autentikasi ke Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 6. Kompilasi & Distribusi Docker Image (Advanced Kriteria)
        run: |
          echo "[INFO] Menambahkan baris kosong dan pengaman dependensi..."
          if [ -f "local_model_dir/requirements.txt" ]; then
            # Trik cerdas Anda agar teks tidak menempel:
            echo "" >> local_model_dir/requirements.txt
            echo "setuptools<70.0.0" >> local_model_dir/requirements.txt
          fi
          
          echo "[INFO] Memulai eksekusi build menggunakan fungsi resmi MLflow..."
          mlflow models build-docker -m local_model_dir -n ${{ secrets.DOCKER_USERNAME }}/klasifikasi-mahasiswa-api:latest --env-manager=local
          
          echo "[INFO] Mengunggah Image ke Docker Hub Registry..."
          docker push ${{ secrets.DOCKER_USERNAME }}/klasifikasi-mahasiswa-api:latest
