name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main # (Ubah jadi master jika branch Anda master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Mengunduh Kode Repositori
        uses: actions/checkout@v4

      - name: 2. Konfigurasi Python Lingkungan
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: 3. Instalasi Pustaka Pendukung & MLflow
        run: |
          python -m pip install --upgrade pip
          pip install "setuptools<70.0.0" wheel
          pip install pandas scikit-learn matplotlib seaborn mlflow==2.11.3

      - name: 4. Mengeksekusi Pelatihan Model (MLflow Project)
        env:
          DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mlflow run . --no-conda

      - name: 5. Autentikasi ke Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 6. Kompilasi & Distribusi Docker Image (Advanced Kriteria)
        run: |
          mlflow models build-docker -m local_model_dir -n ${{ secrets.DOCKER_USERNAME }}/klasifikasi-mahasiswa-api:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/klasifikasi-mahasiswa-api:latest
